[package]
name = "kno3"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
anyhow = "1.0.58"
gdnative = "0.10.1"
itertools = "0.10.3"
lazy_static = "1.4.0"
lerp = "0.4.0"
rand = "0.8.5"
serde = { version = "1.0", features = ["derive", "rc"] }
serde_json = "1.0"
